name: Publish Dockers

on:
  push:
    branches:
      - main

jobs:
  publish-nightly:
    name: "Publish Nightly"
    if: github.event_name != 'release'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/partial-publish.yaml
    with:
      build_version: nightly
      publish_nightly: true


